
# DO NOT EDIT MANUALLY - This file is autogenerated from Asana API Specs

#' Returns a list of all of the custom fields settings on a project, in compact form. Note that, as in all queries to collections which return compact representation, `opt_fields` and `opt_expand` can be used to include more data than is returned in the compact representation. See the getting started guide on [input/output options](/developers/documentation/getting-started/input-output-options) for more information.
#'
#' @param project  {Id} The ID of the project for which to list custom field settings#'
#' @param ...  {Object} Parameters for the request
#' @export
asn_custom_field_settings_find_by_project = function(project, ..., options = list()){
  path = sprintf("/projects/%s/custom_field_settings", project)
  asn_get(endpoint = path, ..., options = options)
}


