# DO NOT EDIT MANUALLY - This file is autogenerated from Asana API Specs
#' OrganizationExports
#'
#'
#'  An _organization_export_ object represents a request to export the complete data of an Organization
#'  in JSON format.
#'  
#'  To export an Organization using this API:
#'  
#'  * Create an `organization_export` [request](#create) and store the id that is returned.\
#'  * Request the `organization_export` every few minutes, until the `state` field contains 'finished'.\
#'  * Download the file located at the URL in the `download_url` field.
#'  
#'  Exports can take a long time, from several minutes to a few hours for large Organizations.
#'  
#'  **Note:** These endpoints are only available to [Service Accounts](/guide/help/premium/service-accounts)
#'  of an [Enterprise](/enterprise) Organization.
#' @name asn_organization_exports
#' @rdname asn_organization_exports
#' @family organization_exports
#' @seealso \link{https://asana.com/developers/api-reference/organization_exports}
NULL

#' Returns details of a previously-requested Organization export.
#'
#' @param organization_export  {Id} Globally unique identifier for the Organization export.#'
#' @param ...  {Object} Parameters for the request
#' @export
#' @family organization_exports
asn_organization_exports_find_by_id = function(organization_export, ..., options = list()){
  path = sprintf("/organization_exports/%s", organization_export)
  asn_get(endpoint = path, ..., options = options)
}


#' This method creates a request to export an Organization. Asana will complete the export at some
#' point after you create the request.
#'
#' @param ...  {Object} Data for the request
#'    organization : {Id} Globally unique identifier for the workspace or organization.
#' @export
#' @family organization_exports
asn_organization_exports_create = function(..., options = list()){
  path =  "/organization_exports"
  asn_post(endpoint = path, ..., options = options)
}


