
# DO NOT EDIT MANUALLY - This file is autogenerated from Asana API Specs

#' Returns details of a previously-requested Organization export.
#'
#' @param organization_export  {Id} Globally unique identifier for the Organization export.#'
#' @param ...  {Object} Parameters for the request
#' @export
asn_organization_exports_find_by_id = function(organization_export, ..., options = list()){
  path = sprintf("/organization_exports/%s", organization_export)
  asn_get(endpoint = path, ..., options = options)
}


#' This method creates a request to export an Organization. Asana will complete the export at some
#' point after you create the request.
#'
#' @param ...  {Object} Data for the request
#'    organization : {Id} Globally unique identifier for the workspace or organization.
#' @export
asn_organization_exports_create = function(..., options = list()){
  path =  "/organization_exports"
  asn_post(endpoint = path, ..., options = options)
}


