
# DO NOT EDIT MANUALLY - This file is autogenerated from Asana API Specs

#' Returns the compact project membership records for the project.
#'
#' @param project  {Id} The project for which to fetch memberships.#'
#' @param ...  {Object} Parameters for the request
#'    [user] : {String} If present, the user to filter the memberships to.
#' @export
asn_project_memberships_get_many = function(project, ..., options = list()){
  path = sprintf("/projects/%s/project_memberships", project)
  asn_get(endpoint = path, ..., options = options)
}


#' Returns the project membership record.
#'
#' @param project  {Id} Globally unique identifier for the project membership.#'
#' @param ...  {Object} Parameters for the request
#' @export
asn_project_memberships_get_single = function(project, ..., options = list()){
  path = sprintf("/project_memberships/%s", project)
  asn_get(endpoint = path, ..., options = options)
}


