# DO NOT EDIT MANUALLY - This file is autogenerated from Asana API Specs
#' ProjectMemberships
#'
#'
#'  With the introduction of "comment-only" projects in Asana, a user's membership
#'  in a project comes with associated permissions. These permissions (whether a
#'  user has full access to the project or comment-only access) are accessible
#'  through the project memberships endpoints described here.
#' @name asn_project_memberships
#' @rdname asn_project_memberships
#' @family project_memberships
#' @seealso \link{https://asana.com/developers/api-reference/project_memberships}
NULL

#' Returns the compact project membership records for the project.
#'
#' @param project  {Id} The project for which to fetch memberships.#'
#' @param ...  {Object} Parameters for the request
#'    [user] : {String} If present, the user to filter the memberships to.
#' @export
#' @family project_memberships
asn_project_memberships_get_many = function(project, ..., options = list()){
  path = sprintf("/projects/%s/project_memberships", project)
  asn_get(endpoint = path, ..., options = options)
}


#' Returns the project membership record.
#'
#' @param project  {Id} Globally unique identifier for the project membership.#'
#' @param ...  {Object} Parameters for the request
#' @export
#' @family project_memberships
asn_project_memberships_get_single = function(project, ..., options = list()){
  path = sprintf("/project_memberships/%s", project)
  asn_get(endpoint = path, ..., options = options)
}


